
# tomcat port
server:
  port: 8080
  
# jsp 
spring:
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp
#  devtools:
#    livereload:
#      enabled: true
      
# mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://treasure.ckanwu0dfli3.ap-northeast-2.rds.amazonaws.com:3306/treasure?serverTimezone=Asia/Seoul
    username: treasure
    password: 7YiVzLxFFLbieig
    
# mybatis
mybatis:
  type-aliases-package: boot.mvc.*
  mapper-locations:
    - /mapper/**/*.xml