
# tomcat port
server:
  port: 9010
  
# jsp 
spring:
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp
  web:
    resources:
      cache:
        period: 43200
#  devtools:
#    livereload:
#      enabled: true
      
# mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/project?serverTimezone=UTC
    username: root
    password: kimyd981201@

# mybatis
mybatis:
  type-aliases-package: boot.mvc.*
  mapper-locations:
    - /mapper/**/*.xml